var annotated_dup =
[
    [ "BH", "d6/d32/namespace_b_h.html", [
      [ "BarnesHut", "d2/d20/class_b_h_1_1_barnes_hut.html", "d2/d20/class_b_h_1_1_barnes_hut" ],
      [ "MortonTree", "d5/d14/class_b_h_1_1_morton_tree.html", "d5/d14/class_b_h_1_1_morton_tree" ],
      [ "params", "de/d3a/class_b_h_1_1params.html", "de/d3a/class_b_h_1_1params" ],
      [ "PointsCopy", "df/d22/class_b_h_1_1_points_copy.html", "df/d22/class_b_h_1_1_points_copy" ],
      [ "TParticleCode", "d2/d1b/struct_b_h_1_1_t_particle_code.html", "d2/d1b/struct_b_h_1_1_t_particle_code" ],
      [ "treeCellT", "d6/d8f/struct_b_h_1_1tree_cell_t.html", "d6/d8f/struct_b_h_1_1tree_cell_t" ]
    ] ],
    [ "VM2D", "d9/dd7/namespace_v_m2_d.html", [
      [ "Airfoil", "db/de9/class_v_m2_d_1_1_airfoil.html", "db/de9/class_v_m2_d_1_1_airfoil" ],
      [ "AirfoilDeformable", "d7/d0e/class_v_m2_d_1_1_airfoil_deformable.html", "d7/d0e/class_v_m2_d_1_1_airfoil_deformable" ],
      [ "AirfoilGeometry", "dd/d6e/class_v_m2_d_1_1_airfoil_geometry.html", "dd/d6e/class_v_m2_d_1_1_airfoil_geometry" ],
      [ "AirfoilParams", "d7/deb/struct_v_m2_d_1_1_airfoil_params.html", "d7/deb/struct_v_m2_d_1_1_airfoil_params" ],
      [ "AirfoilRigid", "db/d33/class_v_m2_d_1_1_airfoil_rigid.html", "db/d33/class_v_m2_d_1_1_airfoil_rigid" ],
      [ "Beam", "d2/dc5/class_v_m2_d_1_1_beam.html", "d2/dc5/class_v_m2_d_1_1_beam" ],
      [ "Boundary", "df/da2/class_v_m2_d_1_1_boundary.html", "df/da2/class_v_m2_d_1_1_boundary" ],
      [ "BoundaryConstLayerAver", "d2/d0a/class_v_m2_d_1_1_boundary_const_layer_aver.html", "d2/d0a/class_v_m2_d_1_1_boundary_const_layer_aver" ],
      [ "BoundaryLinLayerAver", "da/da5/class_v_m2_d_1_1_boundary_lin_layer_aver.html", "da/da5/class_v_m2_d_1_1_boundary_lin_layer_aver" ],
      [ "BoundaryVortexCollocN", "df/dde/class_v_m2_d_1_1_boundary_vortex_colloc_n.html", "df/dde/class_v_m2_d_1_1_boundary_vortex_colloc_n" ],
      [ "ChordPanel", "d3/d47/struct_v_m2_d_1_1_chord_panel.html", "d3/d47/struct_v_m2_d_1_1_chord_panel" ],
      [ "CpuTreeInfo", "dd/d7e/class_v_m2_d_1_1_cpu_tree_info.html", "dd/d7e/class_v_m2_d_1_1_cpu_tree_info" ],
      [ "Gpu", "d0/d75/class_v_m2_d_1_1_gpu.html", "d0/d75/class_v_m2_d_1_1_gpu" ],
      [ "MeasureVP", "d6/db8/class_v_m2_d_1_1_measure_v_p.html", "d6/db8/class_v_m2_d_1_1_measure_v_p" ],
      [ "Mechanics", "d7/dc9/class_v_m2_d_1_1_mechanics.html", "d7/dc9/class_v_m2_d_1_1_mechanics" ],
      [ "MechanicsDeformable", "dc/d54/class_v_m2_d_1_1_mechanics_deformable.html", "dc/d54/class_v_m2_d_1_1_mechanics_deformable" ],
      [ "MechanicsRigidGivenLaw", "d6/de3/class_v_m2_d_1_1_mechanics_rigid_given_law.html", "d6/de3/class_v_m2_d_1_1_mechanics_rigid_given_law" ],
      [ "MechanicsRigidImmovable", "da/d93/class_v_m2_d_1_1_mechanics_rigid_immovable.html", "da/d93/class_v_m2_d_1_1_mechanics_rigid_immovable" ],
      [ "MechanicsRigidOscillPart", "db/d0e/class_v_m2_d_1_1_mechanics_rigid_oscill_part.html", "db/d0e/class_v_m2_d_1_1_mechanics_rigid_oscill_part" ],
      [ "MechanicsRigidRotatePart", "d6/dec/class_v_m2_d_1_1_mechanics_rigid_rotate_part.html", "d6/dec/class_v_m2_d_1_1_mechanics_rigid_rotate_part" ],
      [ "NumericalSchemes", "d2/d76/struct_v_m2_d_1_1_numerical_schemes.html", "d2/d76/struct_v_m2_d_1_1_numerical_schemes" ],
      [ "Passport", "d2/d15/class_v_m2_d_1_1_passport.html", "d2/d15/class_v_m2_d_1_1_passport" ],
      [ "PhysicalProperties", "d1/d4b/struct_v_m2_d_1_1_physical_properties.html", "d1/d4b/struct_v_m2_d_1_1_physical_properties" ],
      [ "Sheet", "de/d8b/class_v_m2_d_1_1_sheet.html", "de/d8b/class_v_m2_d_1_1_sheet" ],
      [ "sweepVectors", "df/ddb/struct_v_m2_d_1_1sweep_vectors.html", "df/ddb/struct_v_m2_d_1_1sweep_vectors" ],
      [ "Velocity", "d7/dfe/class_v_m2_d_1_1_velocity.html", "d7/dfe/class_v_m2_d_1_1_velocity" ],
      [ "VelocityBarnesHut", "d4/d32/class_v_m2_d_1_1_velocity_barnes_hut.html", "d4/d32/class_v_m2_d_1_1_velocity_barnes_hut" ],
      [ "VelocityBiotSavart", "d9/dcc/class_v_m2_d_1_1_velocity_biot_savart.html", "d9/dcc/class_v_m2_d_1_1_velocity_biot_savart" ],
      [ "VirtualWake", "d4/d07/class_v_m2_d_1_1_virtual_wake.html", "d4/d07/class_v_m2_d_1_1_virtual_wake" ],
      [ "VortexesParams", "d2/d48/struct_v_m2_d_1_1_vortexes_params.html", "d2/d48/struct_v_m2_d_1_1_vortexes_params" ],
      [ "Wake", "df/d8f/class_v_m2_d_1_1_wake.html", "df/d8f/class_v_m2_d_1_1_wake" ],
      [ "WakeDataBase", "d1/daf/class_v_m2_d_1_1_wake_data_base.html", "d1/daf/class_v_m2_d_1_1_wake_data_base" ],
      [ "WakeDiscretizationProperties", "db/dd0/struct_v_m2_d_1_1_wake_discretization_properties.html", "db/dd0/struct_v_m2_d_1_1_wake_discretization_properties" ],
      [ "World2D", "d3/d00/class_v_m2_d_1_1_world2_d.html", "d3/d00/class_v_m2_d_1_1_world2_d" ]
    ] ],
    [ "VMlib", "dd/d9a/namespace_v_mlib.html", [
      [ "GeomPoint", "dc/d31/struct_v_mlib_1_1_geom_point.html", "dc/d31/struct_v_mlib_1_1_geom_point" ],
      [ "LogStream", "d1/dd8/class_v_mlib_1_1_log_stream.html", "d1/dd8/class_v_mlib_1_1_log_stream" ],
      [ "nummatrix", "da/d3c/class_v_mlib_1_1nummatrix.html", "da/d3c/class_v_mlib_1_1nummatrix" ],
      [ "numvector", "d6/dd4/class_v_mlib_1_1numvector.html", "d6/dd4/class_v_mlib_1_1numvector" ],
      [ "PairInt", "dc/d31/class_v_mlib_1_1_pair_int.html", "dc/d31/class_v_mlib_1_1_pair_int" ],
      [ "Parallel", "dd/de1/class_v_mlib_1_1_parallel.html", "dd/de1/class_v_mlib_1_1_parallel" ],
      [ "parProp", "d4/dac/struct_v_mlib_1_1par_prop.html", "d4/dac/struct_v_mlib_1_1par_prop" ],
      [ "PassportGen", "d9/d9a/class_v_mlib_1_1_passport_gen.html", "d9/d9a/class_v_mlib_1_1_passport_gen" ],
      [ "Point2D", "da/dd5/class_v_mlib_1_1_point2_d.html", "da/dd5/class_v_mlib_1_1_point2_d" ],
      [ "Point2Df", "d0/df2/class_v_mlib_1_1_point2_df.html", "d0/df2/class_v_mlib_1_1_point2_df" ],
      [ "Point4D", "d6/d90/class_v_mlib_1_1_point4_d.html", "d6/d90/class_v_mlib_1_1_point4_d" ],
      [ "Preprocessor", "da/d46/class_v_mlib_1_1_preprocessor.html", "da/d46/class_v_mlib_1_1_preprocessor" ],
      [ "Queue", "d1/d71/class_v_mlib_1_1_queue.html", "d1/d71/class_v_mlib_1_1_queue" ],
      [ "StreamParser", "db/d04/class_v_mlib_1_1_stream_parser.html", "db/d04/class_v_mlib_1_1_stream_parser" ],
      [ "Task", "d7/db3/class_v_mlib_1_1_task.html", "d7/db3/class_v_mlib_1_1_task" ],
      [ "TimeDiscretizationProperties", "d8/da2/struct_v_mlib_1_1_time_discretization_properties.html", "d8/da2/struct_v_mlib_1_1_time_discretization_properties" ],
      [ "TimersGen", "d5/d12/class_v_mlib_1_1_timers_gen.html", "d5/d12/class_v_mlib_1_1_timers_gen" ],
      [ "TimesGen", "d8/de6/class_v_mlib_1_1_times_gen.html", "d8/de6/class_v_mlib_1_1_times_gen" ],
      [ "TParticleCode", "d2/d12/struct_v_mlib_1_1_t_particle_code.html", "d2/d12/struct_v_mlib_1_1_t_particle_code" ],
      [ "v3D", "d4/dbb/class_v_mlib_1_1v3_d.html", "d4/dbb/class_v_mlib_1_1v3_d" ],
      [ "vmTimer", "d9/d54/class_v_mlib_1_1vm_timer.html", "d9/d54/class_v_mlib_1_1vm_timer" ],
      [ "Vortex2D", "d0/de1/class_v_mlib_1_1_vortex2_d.html", "d0/de1/class_v_mlib_1_1_vortex2_d" ],
      [ "WorldGen", "d6/d3d/class_v_mlib_1_1_world_gen.html", "d6/d3d/class_v_mlib_1_1_world_gen" ]
    ] ],
    [ "OptimizedVelocity", "d9/da5/class_optimized_velocity.html", "d9/da5/class_optimized_velocity" ]
];