#!/bin/bash
#PBS -N VM2D_User
#PBS -S /bin/bash
#PBS -l walltime=48:00:00
#PBS -l nodes=2:ppn=12
#PBS -q bl220
#PBS -d /unicluster/home/guest13/VortTest/run

cat $PBS_NODEFILE

mpirun -machinefile $PBS_NODEFILE -np 2 -map-by slot:pe=12 VM2D > log.log
